# Generated by Django 3.2.6 on 2021-09-01 10:07

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('starting_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ending_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='TLD',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tld', to='web.route')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='saccos',
            field=models.ManyToManyField(blank=True, related_name='saccos', to='web.Sacco'),
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('fare', models.PositiveIntegerField()),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fare', to='web.route')),
            ],
        ),
        migrations.CreateModel(
            name='Commute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('drop_off_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('fare', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.fare')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commutes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('tld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_stops', to='web.tld')),
            ],
            options={
                'unique_together': {('tld', 'point')},
            },
        ),
    ]
