# Generated by Django 3.2.6 on 2021-09-19 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fare',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='fare',
            name='route',
        ),
        migrations.AddField(
            model_name='fare',
            name='sacco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fare', to='web.sacco'),
        ),
    ]
